name: Deploy Next.js

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 92.112.179.231
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /atmosphere
            git pull origin master
            npm run build
            pm2 restart all
